# Site settings
title: Allen's Blog
description: "Allen's Blog"
url: "http://www.allen7wang.info"
author:
  name: "Allen Wang"
  email: "allen7wang@gmail.com"
  url: "http://www.allen7wang.info"

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
