<<<<<<< HEAD
# Site settings
title: Allen7Wang's Blog
email: allen7wang@gmail.com
description: > # this means to ignore newlines until "baseurl:"  
       This is Allen Wang's Blog.
       I believe that practice makes perfect.
       I want to share life experience to others.
baseurl: "/allen7wang.github.io" # the subpath of your site, e.g. /blog/
url: "http://allen7wang.com" # the base hostname & protocol for your site
twitter_username: allen7wang
github_username: allen7wang

# Build settings
markdown: kramdown
=======
baseurl: /
>>>>>>> 226e97da78ee68c546b42d78c6ddef9406a244d1
