# Site Info
title:              "Welcome to the blog"
description:        "allen7wang's blog"
author_name:        "allen7wang" # change this to your name
logo_url:           https://avatars1.githubusercontent.com/u/6808119?v=4  # Get it from GitHub API: https://api.github.com/users/<username>

# Site Settings
url:                https://allen7wang.github.io # main url
baseurl:            /
permalink:          /:title # Post permalink
timezone:           Asia/Shanghai # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
mathjax:            true  # enables support for mathjax - set to 'false' to disable

# Site Build
highlighter:        rouge
markdown:           kramdown
kramdown:
    input:          GFM
sass:
    style:          :compressed

# Other Params
include:            [ "robots.txt" ]
exclude:            [ "LICENSE", "README.md", "CNAME", "vendor", "Gemfile" ]
plugins:
  - jekyll-sitemap



defaults:
  -
    scope:
      path:         ""
    values:
      layout:       "null"
  -
    scope:
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      type:         "posts"
    values:
      layout:       "post"
