# Site settings
title: Allen7Wang's Blog
email: allen7wang@gmail.com
description: > # this means to ignore newlines until "baseurl:"  
       This is Allen Wang's Blog.
       I believe that practice makes perfect.
       I want to share life experience to others.
#baseurl: /
# the subpath of your site, e.g. /blog/
url: http://www.allen7wang.com 
# the base hostname & protocol for your site
twitter_username: allen7wang
github_username: allen7wang

# Build settings
markdown: kramdown
